### ISSUE TITLE
running regression model throws exception. 

### ISSUE THREAD

**Issue by kyuubi-02** [palooney/traitsPredictor#2]
So I was running the code and while running modelrun.py, Half of the program runs fine, precisely, the classification part of the program runs fine, but, regression part throws the following exception

Traceback (most recent call last):
  File "C:\Eclipse Workspace\BEProject2017\modelRun.py", line 81, in <module>
    x.getRated()
  File "C:\Eclipse Workspace\BEProject2017\modelRun.py", line 66, in getRated
    self.getModel()
  File "C:\Eclipse Workspace\BEProject2017\modelRun.py", line 29, in getModel
    m.saveModel()
  File "C:\Eclipse Workspace\BEProject2017\trainProcess.py", line 167, in saveModel
    self.modelYes[item] = pickle.dumps(self.trainModelRegression(item, 1))
  File "C:\Eclipse Workspace\BEProject2017\trainProcess.py", line 112, in trainModelRegression
    clf.fit(sample, label)
  File "C:\Setups\Python\lib\site-packages\sklearn\linear_model\coordinate_descent.py", line 707, in fit
    multi_output=True, y_numeric=True)
  File "C:\Setups\Python\lib\site-packages\sklearn\utils\validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "C:\Setups\Python\lib\site-packages\sklearn\utils\validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 10)) while a minimum of 1 is required.

I have not put the Classification output preceding the following error

**Comment by changyeli** [comment]
Hello,

There is something wrong with your data input.

**Comment by kyuubi-02** [comment]
Can you guide me as to what can be the wrong input. Since all of the data input is according to your code. Any help is appreciated.
